---
htpasswd_output_path: "{{ inventory_dir }}/../files/htpasswd"
oauth:
  htpasswd:
    HTPASSWD_SECRET: "{{ secrets.htpasswd.SECRET_NAME }}"

secret_action: create
secrets:
  htpasswd:
    SECRET_KEY: htpasswd
    SECRET_NAME: htpasswd-secret
    SECRET_VALUE: "{{ lookup('file', htpasswd_output_path) | b64encode }}"

openshift_cluster_content:
- galaxy_requirements:
  - "{{ inventory_dir }}/../galaxy-requirements.yml"
- object: Create HTPasswd auth config
  pre_steps:
  - role: infra-ansible/roles/identity-management/htpasswd-from-dict
    tags:
    - idp-htpasswd
  content:
  - name: Create HTPasswd auth secret
    template: "{{ inventory_dir }}/../.openshift/templates/secret-generic-opaque.yml"
    params_from_vars: "{{ secrets.htpasswd }}"
    action: "{{ secret_action }}"
    namespace: openshift-config
    tags:
    - idp-htpasswd
  - name: Create HTPasswd OAuth CR
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_version }}/ocp-identity-providers/htpasswd.yml"
    params_from_vars: "{{ oauth.htpasswd }}"
    tags:
    - idp-htpasswd
- object: Setup cluster policies
  content:
  - name: Create custom cluster-admin ClusterRoleBinding
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_version }}/role-bindings/user-cluster-rolebinding-template.yml"
    params_from_vars:
      USER: labs-mgr
      ROLE: cluster-admin
    tags:
    - role-bindings
- object: Configure Cluster Monitoring
  content:
  - name: Configure Ephemeral Cluster Monitoring
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_version }}/prometheus/ephemeral-cluster-monitoring.yml"
    params: "{{ inventory_dir }}/../.openshift/params/monitoring/ephemeral-cluster-monitoring.params"
    namespace: openshift-monitoring
    tags:
    - ephemeral-cluster-monitoring
#- object: Configure and Deploy Maintenance Tooling
#  content:
#  - name: "cluster-ops-projects"
#    template: "{{ openshift_templates_raw }}/{{ openshift_templates_version }}/project-requests/create-project.yml"
#    params: "{{ inventory_dir }}/../.openshift/params/cluster-ops/project.params"
#    action: create
#    tags:
#    - cluster-ops
#    - cluster-ops-projects
#  - name: "cronjob-prune-builds"
#    namespace: "cluster-ops"
#    template: "https://raw.githubusercontent.com/redhat-cop/openshift-management/{{ openshift_management_version }}/jobs/cronjob-prune-builds-deployments.yml"
#    params: "{{ inventory_dir }}/../.openshift/params/cluster-ops/prune-builds.params"
#    tags:
#    - cluster-ops
#    - cluster-ops-prune-builds
#  - name: "cronjob-prune-deployments"
#    namespace: "cluster-ops"
#    template: "https://raw.githubusercontent.com/redhat-cop/openshift-management/{{ openshift_management_version }}/jobs/cronjob-prune-builds-deployments.yml"
#    params: "{{ inventory_dir }}/../.openshift/params/cluster-ops/prune-deployments.params"
#    tags:
#    - cluster-ops
#    - cluster-ops-prune-deployments
#  - name: "cronjob-prune-images"
#    namespace: "cluster-ops"
#    template: "https://raw.githubusercontent.com/redhat-cop/openshift-management/{{ openshift_management_version }}/jobs/cronjob-prune-images.yml"
#    params: "{{ inventory_dir }}/../.openshift/params/cluster-ops/prune-images.params"
#    tags:
#    - cluster-ops
#    - cluster-ops-prune-images
#  - name: "cronjob-prune-projects"
#    namespace: "cluster-ops"
#    template: "https://raw.githubusercontent.com/redhat-cop/openshift-management/{{ openshift_management_version }}/jobs/cronjob-prune-projects.yaml"
#    params: "{{ inventory_dir }}/../.openshift/params/cluster-ops/prune-projects.params"
#    tags:
#    - cluster-ops
#    - cluster-ops-prune-projects
