apiVersion: v1
kind: Template
metadata:
  name: secret-generic-opaque
objects:
- apiVersion: v1
  type: Opaque
  data:
    ${SECRET_KEY}: ${SECRET_VALUE}
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
parameters:
- description: The name of the key used inside of the secret
  displayName: The name of the key used inside of the secret
  name: SECRET_KEY
  required: true
- description: The name for the newly created secret
  displayName: Secret name
  name: SECRET_NAME
  required: true
- description: Base64 encoding of the file
  displayName: Secret value
  name: SECRET_VALUE
  required: true
